server:
  port: 8080
spring:
  application:
    name: cloud-consumer-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      # default-zone: com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server